### ISSUE TITLE
Cannot compile Code on Solidity Remix Browser

### ISSUE THREAD

**Issue by tanmaybhardwaj** [zupzup/solidity-example-crowdfunding#1]
Hi,

I am using Solidity Remix Browser version 0.4.13 to run the code.
Simply coped the entire code and tried to compile but got error message 
"callback contain no result Error: Error: VM Exception while executing eth_estimateGas: invalid opcode".
Request to provide solutions for this issue.

Regards
Tanmay

**Comment by zupzup** [comment]
solidity moves pretty quickly - for better or for worse :)

i'll happily accept a pr for this.

**Comment by LikitaA** [comment]
which framework did you use??
regards,
Likita

**Comment by zupzup** [comment]
framework for what exactly?

**Comment by LikitaA** [comment]
Like truffle or embark or any other?
In remix I'm getting errors??

**Comment by zupzup** [comment]
No framework. Keep in mind, that the repo and code is about 1 year old, so it shouldn't be surprising, that it doesn't work with the most recent versions of solidity.
